### ISSUE TITLE
Feature Request: Use deleimiter for indexed Variables

### ISSUE THREAD

**Issue by jfh1911** [gernst/korn#3]
Right now, Korn adds indices to the variables for the SMT Output.

Is it possible to add any delimiter-char (e.g. `@` or anything else that is not/rarely used in variable names) to the variables?

(Right now it is hard / impossible to determine, if `v15` is `v1@5` or `v@15`)

In addition, there might be rare corner cases where this also causes issues with same variable names.

**Comment by gernst** [comment]
See 02e0ba6
